services:
  mysql:
    image: mysql:8.0
    container_name: drun-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iframe_dashboard
      MYSQL_USER: drun_user
      MYSQL_PASSWORD: drun_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: .
    container_name: drun-backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: drun_user
      DB_PASSWORD: drun_password
      DB_NAME: iframe_dashboard
      PORT: 8081
    ports:
      - "30081:8081"
    restart: unless-stopped

volumes:
  mysql_data: 